# Generated by Django 2.2.5 on 2019-09-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('desc', models.CharField(max_length=200)),
                ('deadline', models.DateField(verbose_name='Deadline')),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
    ]
